import type {Metadata} from "next";
import {Poppins} from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ui/ClientLayout";

export const poppins = Poppins({
    subsets: ["latin"],
    display: 'swap',
    weight: '400'
});

export const metadata: Metadata = {
    title: "Home - Jamkrindo",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en" className={poppins.className}>
        <body className="antialiased">
        <ClientLayout>{children}</ClientLayout>
        </body>
        </html>
    );
}
